# Generated by Django 2.2.11 on 2020-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='titulo',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='texto',
            new_name='textoCentro',
        ),
        migrations.AddField(
            model_name='info',
            name='horario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='imagenCentro',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='imagenPerfil',
            field=models.ImageField(default=2, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='textoPerfil',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloCentro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloPerfil',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloPrincipal',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
