# Generated by Django 2.2.11 on 2020-04-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradablog',
            name='destacados',
            field=models.BooleanField(default=False),
        ),
    ]
