# Generated by Django 2.2.11 on 2020-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_entradablog_destacados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patologia',
            old_name='nombre',
            new_name='patologia',
        ),
        migrations.RemoveField(
            model_name='patologia',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='patologia',
            name='sistema',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
