# Generated by Django 2.2.11 on 2020-05-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200504_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCentro', models.CharField(max_length=80, null=True)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('horario', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='info',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='info',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='info',
            name='tel',
        ),
    ]
