# Generated by Django 2.2.11 on 2020-05-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200504_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='patologia',
            old_name='patologia',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='patologia',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='app.Sistema'),
            preserve_default=False,
        ),
    ]
