# Generated by Django 2.2.11 on 2020-05-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200506_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patologia',
            name='sistema',
            field=models.ForeignKey(max_length=80, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='app.Sistema'),
        ),
    ]
