# Generated by Django 2.2.11 on 2020-05-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200507_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistema',
            options={'ordering': ['nombresistema']},
        ),
    ]
