# Generated by Django 2.2.11 on 2020-05-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200508_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='tituloPerfil',
            new_name='nombreDr',
        ),
    ]
