# Generated by Django 2.2.10 on 2020-05-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200511_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonios',
            new_name='Testimonio',
        ),
    ]
