# Generated by Django 2.2.10 on 2020-05-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200511_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonio',
            new_name='Testimonios',
        ),
    ]
