# Generated by Django 2.2.10 on 2020-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200511_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('edad', models.IntegerField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('fecha_publicacion', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonios',
        ),
    ]
