# Generated by Django 2.2.10 on 2020-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200511_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(default='testimonios/no-img.png', upload_to='testimonios'),
        ),
    ]
