# Generated by Django 2.2.10 on 2020-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_testimonio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='imagen',
            field=models.ImageField(default='testimonios/profile.png', upload_to='testimonios'),
        ),
    ]
