# Generated by Django 2.2.11 on 2020-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200512_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='nombre_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='nombre_es',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
