# Generated by Django 2.2.10 on 2020-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200515_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='direccion_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='direccion_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombreCentro_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombreCentro_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='textoCentro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='textoCentro_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='textoPerfil_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='textoPerfil_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloCentro_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloCentro_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloPrincipal_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='tituloPrincipal_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='nombre_en',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='testimonio',
            name='nombre_es',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
