# Generated by Django 2.2.11 on 2020-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200515_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='nombrepatologia_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='patologia',
            name='nombrepatologia_es',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='nombresistema_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='nombresistema_es',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
