# Generated by Django 2.2.11 on 2020-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200516_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistema',
            options={'ordering': ['nombresistema_es']},
        ),
    ]
