# Generated by Django 2.2.11 on 2020-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200522_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patologia',
            options={'ordering': ['nombrepatologia_es']},
        ),
        migrations.AddField(
            model_name='contacto',
            name='redSocial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
