# Generated by Django 2.2.11 on 2020-05-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200525_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='redSocial',
            new_name='instagram',
        ),
        migrations.AddField(
            model_name='contacto',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
    ]
