# Generated by Django 2.2.12 on 2020-05-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200525_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='horario',
        ),
    ]
