# Generated by Django 2.2.12 on 2020-05-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_contacto_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info Inicio', 'verbose_name_plural': 'Info Inicio'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='horario',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
