# Generated by Django 2.2.12 on 2020-05-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200526_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Inicio',
        ),
    ]
